### PR TITLE
init_project

### PR DESCRIPTION
**Pull request by VoHongNghiep**

### CODE REVIEW

**Comment by VoHongNghiep** [comment]
Screenshot from 2022-08-05 14-38-44

**Comment by VoHongNghiep** [comment]
ready

**Comment by VoHongNghiep** [comment]
ready

**Comment by VoHongNghiep** [comment]
ready

**Review by ghost — COMMENTED** [review]
config lại em nhé

**Comment by VoHongNghiep** [comment]
ready

**Comment by ngocvt-0484** [comment]
merged

**Pull request merged**
